force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Selectors/EmployeeSelector.cls
/**
 * @description Selector class for Employee__c object.
 */
public with sharing class EmployeeSelector extends fflib_SObjectSelector {
  /**
   * @description Constructor for EmployeeSelector.
   * @return list<Schema.SObjectField> - List of SObject fields to be selected.
   */
  public List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField>{
      Employee__c.Name,
      Employee__c.OwnerId,
      Employee__c.Last_Name__c,
      Employee__c.First_Name__c,
      Employee__c.Tenure__c
    };
  }

  /**
   * @description Returns the SObject type for the selector.
   * @return Schema.SObjectType - The SObject type for Employee__c.
   */
  public Schema.SObjectType getSObjectType() {
    return Employee__c.sObjectType;
  }

  /**
   * @description Selects Employee records by their IDs.
   * @param idSet - Set of IDs to select Employees by.
   * @return List<Employee__c> - List of Employee records matching the provided IDs.
   */
  public List<Employee__c> selectById(Set<ID> idSet) {
    return (List<Employee__c>) selectSObjectsById(idSet);
  }

  /**
   * @description Selects all Employee records up to a specified limit.
   * @return List<Employee__c> - List of all Employee records.
   */
  public List<Employee__c> selectAll() {
    return this.selectAll(50000);
  }

  /**
   * @description Selects all Employee records up to a specified limit.
   * @param recordLimit - Maximum number of records to return.
   * @return List<Employee__c> - List of all Employee records.
   */
  public List<Employee__c> selectAll(Integer recordLimit) {
    return (List<Employee__c>) Database.query(
      newQueryFactory().setLimit(recordLimit).toSOQL()
    );
  }
}