force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Factories/TestEmployeeFactory.cls
/**
 * @description Factory class for generating test Employee__c records.
 */
@isTest
public class TestEmployeeFactory {
  /**
   * @description Generates a specified number of Employee__c records.
   * @param numEmployees The number of Employee__c records to create.
   * @param doInsert Whether to insert the Employee__c records into the database.
   * @param uow The unit of work to use for inserting the Employee__c records.
   * @return An array of created Employee__c records.
   */
  public static Employee__c[] generateEmployees(
    Integer numEmployees,
    Boolean doInsert,
    fflib_SObjectUnitOfWork uow
  ) {
    TestFactory.clearData();
    List<Employee__c> employees = new List<Employee__c>();

    for (Integer i = 0; i < numEmployees; i++) {
      Employee__c emp = new Employee__c(
        Name = 'e-' + String.valueOf(100 + i),
        First_Name__c = 'FirstName' + String.valueOf(i),
        Last_Name__c = 'LastName' + String.valueOf(i),
        Tenure__c = i + 1
      );
      employees.add(emp);
    }

    if (doInsert) {
      uow.registerNew(employees);
      uow.commitWork();
    }
    return employees;
  }
}