force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestEmployeeChangeTrigger.cls
/**
 * @description Test class for Employee Change Event trigger.
 */
@isTest
public class TestEmployeeChangeTrigger {
  /**
   * @description Test method for creating and updating an Employee record.
   */
  @isTest
  static void testCreateAndUpdateEmployee() {
    Test.enableChangeDataCapture();

    insert new Employee__c(
      Name = 'e-101',
      First_Name__c = 'Astro',
      Last_Name__c = 'Test',
      Tenure__c = 1
    );

    Test.getEventBus().deliver();

    Task[] taskList = [SELECT Id, Subject FROM Task];
    System.assertEquals(
      1,
      taskList.size(),
      'The change event trigger did not create the expected task.'
    );

    Employee__c[] empRecords = [
      SELECT Id, OwnerId, First_Name__c, Tenure__c
      FROM Employee__c
    ];

    Employee__c emp = empRecords[0];
    emp.First_Name__c = 'Codey';
    emp.Tenure__c = null;
    update emp;

    Test.getEventBus().deliver();

    Task[] taskList2 = [SELECT Id, Subject FROM Task];
    System.assertEquals(
      2,
      taskList2.size(),
      'The change event trigger did not create the expected task.'
    );
  }
}